/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SqlSequelRouteImport } from './routes/sql.$sequel'
import { Route as AreasAreaRouteImport } from './routes/areas.$area'

const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlSequelRoute = SqlSequelRouteImport.update({
  id: '/sql/$sequel',
  path: '/sql/$sequel',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaRoute = AreasAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  id: '__root__' | '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasRoute: typeof AreasRouteWithChildren
  SqlSequelRoute: typeof SqlSequelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql/$sequel': {
      id: '/sql/$sequel'
      path: '/sql/$sequel'
      fullPath: '/sql/$sequel'
      preLoaderRoute: typeof SqlSequelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$area': {
      id: '/areas/$area'
      path: '/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof AreasAreaRouteImport
      parentRoute: typeof AreasRoute
    }
  }
}

interface AreasRouteChildren {
  AreasAreaRoute: typeof AreasAreaRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasAreaRoute: AreasAreaRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasRoute: AreasRouteWithChildren,
  SqlSequelRoute: SqlSequelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
