/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AreasImport } from './routes/areas'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SqlSequelImport } from './routes/sql.$sequel'
import { Route as AreasAreaImport } from './routes/areas.$area'

// Create/Update Routes

const AreasRoute = AreasImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SqlSequelRoute = SqlSequelImport.update({
  id: '/sql/$sequel',
  path: '/sql/$sequel',
  getParentRoute: () => rootRoute,
} as any)

const AreasAreaRoute = AreasAreaImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AreasRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasImport
      parentRoute: typeof rootRoute
    }
    '/areas/$area': {
      id: '/areas/$area'
      path: '/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof AreasAreaImport
      parentRoute: typeof AreasImport
    }
    '/sql/$sequel': {
      id: '/sql/$sequel'
      path: '/sql/$sequel'
      fullPath: '/sql/$sequel'
      preLoaderRoute: typeof SqlSequelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AreasRouteChildren {
  AreasAreaRoute: typeof AreasAreaRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasAreaRoute: AreasAreaRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas': typeof AreasRouteWithChildren
  '/areas/$area': typeof AreasAreaRoute
  '/sql/$sequel': typeof SqlSequelRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  id: '__root__' | '/' | '/about' | '/areas' | '/areas/$area' | '/sql/$sequel'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasRoute: typeof AreasRouteWithChildren
  SqlSequelRoute: typeof SqlSequelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasRoute: AreasRouteWithChildren,
  SqlSequelRoute: SqlSequelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/areas",
        "/sql/$sequel"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/areas": {
      "filePath": "areas.tsx",
      "children": [
        "/areas/$area"
      ]
    },
    "/areas/$area": {
      "filePath": "areas.$area.tsx",
      "parent": "/areas"
    },
    "/sql/$sequel": {
      "filePath": "sql.$sequel.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
