name: build and deploy

on:
  workflow_dispatch:
  push:
    branches: ["develop"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: generate types
        run: ./generate-types.sh
      - name: run unit tests
        run: npm run test
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: run e2e tests
        run: npm run e2e
      - name: build app
        run: npm run build
      - name: upload pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v5
